# Generated by Django 3.2.8 on 2021-12-19 10:54

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_saves_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='buys',
            fields=[
                ('key', models.IntegerField(default=event.models.generateID, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('eventID', models.IntegerField()),
            ],
            options={
                'unique_together': {('email', 'eventID')},
            },
        ),
    ]
