# Generated by Django 3.2.8 on 2021-12-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
