# Generated by Django 4.1.dev20211020064019 on 2021-12-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='UserID',
            new_name='userID',
        ),
    ]
