# Generated by Django 4.1.dev20211020064019 on 2021-12-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_userid_userdata_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
